#https://github.com/SeleniumHQ/docker-selenium
version: '3'
services:
  nbdatascience: 
    image: aabor/nbdatascience:1.0
    build: nbdatascience/.
    volumes:
      - /Users/$USER/projects:/home/jovyan/work
      - /Users/$USER/mt5:/home/jovyan/work/mt5
      - /Users/aabor/Library/Application Support/MetaTrader 5/Bottles/metatrader5/drive_c/Program Files/MetaTrader 5/MQL5/Files/updates:/home/jovyan/work/mt5/updates
      - /Users/$USER/.jupyter:/home/jovyan/.jupyter
      - /Users/$USER/.ipython:/home/jovyan/.ipython
      - /Users/$USER/.gitconfig:/home/jovyan/.gitconfig
      - /Users/$USER/.gitignore_global:/home/jovyan/.gitignore_global
      - /Users/$USER/.aws:/home/jovyan/.aws
      - /Users/$USER/.ssh:/home/jovyan/.ssh
      - /Users/$USER/.gnupg:/home/jovyan/.gnupg
      - /Users/$USER/.password-store:/home/jovyan/.password-store
      - /Users/$USER/.matplotlib:/home/jovyan/.matplotlib
      - /Users/$USER/.keras:/home/jovyan/.keras
      - /Users/$USER/.kaggle:/home/jovyan/.kaggle
    ports:
      - 8888:8888
    environment:
      - TZ="PDT"
    restart: always

