#https://github.com/SeleniumHQ/docker-selenium
version: '3'
services:
  nbdatascience: 
    image: aabor/nbdatascience
    build: nbdatascience/.
    volumes:
      - /Users/$USER/MEGAsync/mt5:/home/jovyan/mt5
      - /home/$USER/.jupyter:/home/jovyan/.jupyter
      - /home/$USER/.ipython:/home/jovyan/.ipython
      - /home/$USER/.gitconfig:/home/jovyan/.gitconfig
      - /home/$USER/.aws:/home/jovyan/.aws
      - /home/$USER/.ssh:/home/jovyan/.ssh
      - /home/$USER/.gnupg:/home/jovyan/.gnupg
      - /home/$USER/.password_store:/home/jovyan/.password_store
      - /home/$USER/.matplotlib:/home/jovyan/.matplotlib
      - /home/$USER/.keras:/home/jovyan/.keras
      - /home/$USER/.kaggle:/home/jovyan/.kaggle
      - /home/$USER/.ssh:/home/jovyan/.ssh/  
    ports:
      - 10000:8888
    environment:
      - TZ="PDT"
    restart: always

