#https://github.com/SeleniumHQ/docker-selenium
version: '3'
services:
  nbdatascience: 
    image: aabor/nbdatascience:2.0
    build: nbdatascience/.
    volumes:
      - $HOME:/home/jovyan
    ports:
      - 8888:8888
      - 8501:8501
    environment:
      - TZ="PDT"
      - OPENAI_API_KEY=${OPENAI_GEONAI_API_KEY}
      - LLAMA_INDEX_CACHE_DIR=/home/jovyan/.cache/llama_index
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.langchain.plus
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - WHYLABS_DEFAULT_ORG_ID=${WHYLOG_ORG_ID}
      - LAMINI_API_KEY=${LAMINI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - WHYLABS_API_KEY=${WHYLABS_API_KEY}
      - WHYLABS_DEFAULT_DATASET_ID=model-1
    restart: always
  # grobit:
  #   image: grobid/grobid:0.8.0
  #   restart: unless-stopped
  #   volumes:
  #     - $HOME/.grobit/config:/opt/grobid/grobid-home/config
  #   ports:
  #     - 8070:8070
  postgis:
    image: postgis/postgis
    build: postgis/.    
    restart: unless-stopped
    environment:
      - POSTGRES_USER=u-postgis
      - POSTGRES_PASSWORD=p-postgis
      - CHATGPT_CONFIG_DATABASE=configuration
      - BUS_PORTLAND_CONFIG_DATABASE=bus-portland-configuration
    volumes:
      - $HOME/.db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 60s
      retries: 5
