#https://github.com/SeleniumHQ/docker-selenium
version: '3'
services:
  nbdatascience: 
    image: aabor/nbdatascience:2.0
    build: nbdatascience/.
    volumes:
      - /Users/$USER/projects:/home/jovyan/work
      - /Users/$USER/mt5:/mnt/efs/mt5
      - /Users/aabor/Library/Application Support/MetaTrader 5/Bottles/metatrader5/drive_c/Program Files/MetaTrader 5/MQL5/Files/updates:/mnt/efs/mt5/updates
      - /Users/$USER/.jupyter:/home/jovyan/.jupyter
      - /Users/$USER/.ipython:/home/jovyan/.ipython
      - /Users/$USER/.gitconfig:/home/jovyan/.gitconfig
      - /Users/$USER/.gitignore_global:/home/jovyan/.gitignore_global
      - /Users/$USER/.aws:/home/jovyan/.aws
      - /Users/$USER/.ssh:/home/jovyan/.ssh
      - /Users/$USER/.gnupg:/home/jovyan/.gnupg
      - /Users/$USER/.password-store:/home/jovyan/.password-store
      - /Users/$USER/.matplotlib:/home/jovyan/.matplotlib
      - /Users/$USER/.keras:/home/jovyan/.keras
      - /Users/$USER/.kaggle:/home/jovyan/.kaggle
      - /Users/$USER/.netrc:/home/jovyan/.netrc
      - /Users/$USER/.db/sqlite3:/db/sqlite3
      - /Users/$USER/.db/postgres:/db/postgres
    ports:
      - 8888:8888
    environment:
      - TZ="PDT"
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.langchain.plus
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - WHYLABS_DEFAULT_ORG_ID=${WHYLOG_ORG_ID}
      - WHYLABS_API_KEY=${WHYLABS_API_KEY}
      - WHYLABS_DEFAULT_DATASET_ID=model-1
    restart: always
  postgis:
    image: postgis/postgis
    build: postgis/.    
    restart: unless-stopped
    environment:
      - POSTGRES_USER=u-postgis
      - POSTGRES_PASSWORD=p-postgis
      - CHATGPT_CONFIG_DATABASE=configuration
      - BUS_PORTLAND_CONFIG_DATABASE=bus-portland-configuration
    volumes:
      - /Users/$USER/.db/postgres:/var/lib/postgresql/data
    # ports:
    #   - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 60s
      retries: 5
