pipeline {
    agent any
    stages {
        stage('Build') {
            environment { 
                USER=credentials('jenkins-current-user')
                DOCKER_CREDS=credentials('jenkins-docker-credentials')
            }            
            steps {
                echo 'Building..'
                sh '''
                    export GIT_VERSION=$(git describe --tags | sed s/v//)
                    docker-compose build
                    docker tag $USER/nbdatascience:latest $USER/nbdatascience:$GIT_VERSION
                    docker system prune -f
                '''
                sh '''
                    echo "login to docker"
                    docker login -u $DOCKER_CREDS_USR  -p $DOCKER_CREDS_PSW
                    export GIT_VERSION=$(git describe --tags | sed s/v//)
                    echo $GIT_VERSION
                    echo "Pushing nbdatascience:$GIT_VERSION to docker hub"
                    docker push aabor/nbdatascience:$GIT_VERSION
                    echo "starting docker containers"
                    docker-compose up -d --remove-orphans
                '''
                mail    body: 'containers selenium-hub, chrome, nbdatascience started',
                        from: 'aaborochkin@gmail.com',
                        subject: 'jupyter successfully rolled out',
                        to: 'aaborochkin@gmail.com'  
            }
            post {
                always{
                    cleanWs()
                    sh '''
                        pwd
                        ls
                        echo "Finishing.."
                    '''
                }
            }
        }
    }
}
